server:
  port: 8080

spring:
  application:
    name: pet-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/petTest
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

token:
  expiration_time: 86400000
  secret: ekswlsmstptkddptjrkwkdrnldudnsalsldjcuvlsturkddkwl

